[package]
name = "rds"
version = "0.1.0"
edition = "2018"
authors = ["Parham Alvani <parham.alvani@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
