---
name: ci
on:
  push:

jobs:
  cargo:
    name: cargo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.projects }}
    strategy:
      matrix:
        projects:
          - phonebook
          - rds
          - word-count-parham
          - recho
          - data-in-depth
          - elipu
    steps:
      - name: checkout sources
        uses: actions/checkout@v5
      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: run cargo fmt
        run: cargo fmt --all -- --check
      - name: run cargo clippy
        run: cargo clippy -- -D warnings
      - run: |
          if [ -f docker-compose.yml ]; then
            docker-compose up -d
          fi
      - run: cargo test
